ALTER TABLE items RENAME COLUMN calories_per_100 TO calories_per_100g;
ALTER TABLE items RENAME COLUMN fats_per_100 TO fats_per_100g;
ALTER TABLE items RENAME COLUMN fats_saturated_per_100 TO fats_saturated_per_100g;
ALTER TABLE items RENAME COLUMN carbs_per_100 TO carbs_per_100g;
ALTER TABLE items RENAME COLUMN carbs_sugar_per_100 TO carbs_sugar_per_100g;
ALTER TABLE items RENAME COLUMN carbs_slow_release_per_100 TO carbs_slow_release_per_100g;
ALTER TABLE items RENAME COLUMN carbs_fast_release_per_100 TO carbs_fast_release_per_100g;
ALTER TABLE items RENAME COLUMN proteins_per_100 TO proteins_per_100g;
ALTER TABLE items RENAME COLUMN salt_per_100 TO salt_per_100g;
