name: Build and Test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v4
      with:
        go-version: '1.23.1'

    - name: Install sqlite3
      run: sudo apt-get install sqlite3

    - name: Install go dependencies
      run: make go-deps

    - name: Build
      run: make build

    - name: Generate test coverage from unit tests
      run: make unit-test

    - name: Generate test coverage from integration tests
      run: make integration-test

    - name: Check test coverage
      uses: vladopajic/go-test-coverage@v2
      with:
        config: ./.github/.testcoverage.yml
        git-token: ${{ github.ref_name == 'main' && secrets.GITHUB_TOKEN || '' }}
        git-branch: badges
