# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v4
      with:
        go-version: '1.23.1'

    - name: Install sqlite3
      run: sudo apt-get install sqlite3

    - name: Install sqlc
      run: go install github.com/sqlc-dev/sqlc/cmd/sqlc@v1.27.0

    - name: Install golang-migrate with the sqlite3 driver
      run: go install -tags 'sqlite3' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

    - name: Build
      run: make build

    - name: Generate test coverage
      run: go test ./... -v -coverprofile=./cover.out -covermode=atomic -coverpkg=./...

    - name: Check test coverage
      uses: vladopajic/go-test-coverage@v2
      with:
        config: ./.github/.testcoverage.yml
        git-token: ${{ github.ref_name == 'main' && secrets.GITHUB_TOKEN || '' }}
        git-branch: badges
